"use client";
import { useEffect, useRef, useState } from "react";

type SpeechRecognitionLike = { lang:string; continuous:boolean; interimResults:boolean; start:()=>void; stop:()=>void; onresult:((event:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void)|null; onend:(()=>void)|null; onerror:((event:{error?:string})=>void)|null };
type SpeechRecognitionCtor = new () => SpeechRecognitionLike;
type SpeechWindow = Window & { SpeechRecognition?:SpeechRecognitionCtor; webkitSpeechRecognition?:SpeechRecognitionCtor };

export default function Composer({onSend,onStop,busy,webSearch,onToggleResearch}:{onSend:(text:string,imageDataUrl?:string)=>void;onStop:()=>void;busy:boolean;webSearch:boolean;onToggleResearch:()=>void}) {
 const [value,setValue]=useState(""); const [listening,setListening]=useState(false); const [voiceError,setVoiceError]=useState(""); const [imageDataUrl,setImageDataUrl]=useState(""); const [imageName,setImageName]=useState("");
 const inputRef=useRef<HTMLTextAreaElement>(null); const fileRef=useRef<HTMLInputElement>(null); const recognitionRef=useRef<SpeechRecognitionLike|null>(null);
 useEffect(()=>()=>{recognitionRef.current?.stop();window.speechSynthesis?.cancel();},[]);
 function resize(){const el=inputRef.current;if(!el)return;el.style.height="0px";el.style.height=`${Math.min(el.scrollHeight,180)}px`;}
 function submit(){const text=value.trim();if(!text||busy)return;onSend(text,imageDataUrl||undefined);setValue("");setImageDataUrl("");setImageName("");requestAnimationFrame(resize);}
 async function attachImage(file?:File){const selected=file??fileRef.current?.files?.[0];if(!selected)return;if(!/^image\/(png|jpe?g|webp)$/i.test(selected.type)){setVoiceError("Use PNG, JPG, JPEG, or WebP.");return;}if(selected.size>12*1024*1024){setVoiceError("Image must be 12 MB or smaller.");return;}try{const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>typeof reader.result==="string"?resolve(reader.result):reject(new Error("Could not read image."));reader.onerror=()=>reject(reader.error||new Error("Could not read image."));reader.readAsDataURL(selected);});const preview=await new Promise<string>((resolve)=>{const image=new Image();image.onload=()=>{const maxSide=1600,scale=Math.min(1,maxSide/Math.max(image.naturalWidth||image.width,image.naturalHeight||image.height)),width=Math.max(1,Math.round((image.naturalWidth||image.width)*scale)),height=Math.max(1,Math.round((image.naturalHeight||image.height)*scale)),canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const ctx=canvas.getContext("2d");if(!ctx){resolve(data);return;}ctx.drawImage(image,0,0,width,height);resolve(canvas.toDataURL("image/webp",.82));};image.onerror=()=>resolve(data);image.src=data;});setImageDataUrl(preview);setImageName(selected.name);setVoiceError("");}catch(error){setVoiceError(error instanceof Error?error.message:"Could not attach image.");}}
 function voice(){const w=window as SpeechWindow,Recognition=w.SpeechRecognition??w.webkitSpeechRecognition;setVoiceError("");if(!Recognition){setVoiceError("Voice input is not supported in this browser.");return;}if(listening){recognitionRef.current?.stop();return;}const recognition=new Recognition();recognition.lang=navigator.language||"en-IN";recognition.continuous=false;recognition.interimResults=false;recognition.onresult=e=>{const text=e.results[0]?.[0]?.transcript??"";if(text)setValue(v=>`${v}${v?" ":""}${text}`);};recognition.onerror=e=>{setListening(false);recognitionRef.current=null;setVoiceError(e.error==="not-allowed"?"Microphone permission was denied.":"Voice input could not start. Try again.");};recognition.onend=()=>{setListening(false);recognitionRef.current=null;};recognitionRef.current=recognition;setListening(true);try{recognition.start();}catch{setListening(false);recognitionRef.current=null;setVoiceError("Voice input could not start. Try again.");}}
 const disabled=!value.trim()||busy;
 return <div className="composer-wrap"><div className="composer">{imageDataUrl&&<div className="attachment-chip"><img src={imageDataUrl} alt="Attached image preview"/><span>{imageName||"Image attached"}</span><button type="button" aria-label="Remove attached image" onClick={()=>{setImageDataUrl("");setImageName("");}}>×</button></div>}<textarea ref={inputRef} value={value} onChange={e=>{setValue(e.target.value);setVoiceError("");requestAnimationFrame(resize);}} onInput={resize} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();submit();}}} placeholder={busy?"Ambi is responding…":"Message Ambi…"} rows={1} aria-label="Message Ambi"/><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void attachImage(e.target.files?.[0])}/><div className="composer-row"><div className="composer-tools"><button className={`tool ${webSearch?"active":""}`} onClick={onToggleResearch} type="button" aria-pressed={webSearch}>⌁ Research</button><button className={`tool ${listening?"active":""}`} onClick={voice} type="button">{listening?"◉ Listening":"◉ Voice"}</button><button className="tool" onClick={()=>fileRef.current?.click()} type="button">⌕ Attach</button></div><span className="hint">{imageDataUrl?"Attached image ready":"Shift+Enter for a new line"}</span>{busy?<button className="send stop" onClick={onStop} type="button">Stop</button>:<button className="send" onClick={submit} type="button" disabled={disabled}>Send</button>}</div>{voiceError&&<div className="composer-error" role="status">{voiceError}</div>}</div></div>;
}
