"use client";

import { useEffect, useRef, useState } from "react";
import { detectRequestIntent, type RequestIntent } from "@/lib/tools/intents";

type SpeechRecognitionLike = { lang:string; continuous:boolean; interimResults:boolean; start:()=>void; stop:()=>void; onresult:((event:{results:ArrayLike<ArrayLike<{transcript:string}>>})=>void)|null; onend:(()=>void)|null; onerror:((event:{error?:string})=>void)|null };
type SpeechRecognitionCtor = new()=>SpeechRecognitionLike;
type SpeechWindow = Window & { SpeechRecognition?:SpeechRecognitionCtor; webkitSpeechRecognition?:SpeechRecognitionCtor };
type MediaMode = "chat"|"pexels-photo"|"pexels-video";
function mediaModeForIntent(intent:RequestIntent):MediaMode{return intent==="pexels-photo"?"pexels-photo":intent==="pexels-video"?"pexels-video":"chat";}

export default function Composer({onSend,onStop,busy,webSearch,onToggleResearch}:{onSend:(text:string,imageDataUrl?:string)=>void;onStop:()=>void;busy:boolean;webSearch:boolean;onToggleResearch:()=>void;}){
 const [value,setValue]=useState("");const[listening,setListening]=useState(false);const[voiceError,setVoiceError]=useState("");const[imageDataUrl,setImageDataUrl]=useState("");const[imageName,setImageName]=useState("");const[manualMode,setManualMode]=useState<MediaMode>("chat");
 const inputRef=useRef<HTMLTextAreaElement>(null);const fileRef=useRef<HTMLInputElement>(null);const recognitionRef=useRef<SpeechRecognitionLike|null>(null);
 function resize(){const el=inputRef.current;if(!el)return;el.style.height="0px";el.style.height=`${Math.min(el.scrollHeight,180)}px`;}
 useEffect(()=>()=>{recognitionRef.current?.stop();if("speechSynthesis"in window)window.speechSynthesis.cancel();},[]);
 async function submit(){const text=value.trim();if(!text||busy)return;const detected=manualMode==="chat"?detectRequestIntent(text):manualMode;if(detected==="pexels-photo"||detected==="pexels-video"){window.dispatchEvent(new CustomEvent("ambi:search-pexels",{detail:{query:text,type:detected==="pexels-video"?"video":"photo"}}));}else onSend(text,imageDataUrl||undefined);setValue("");setImageDataUrl("");setImageName("");setManualMode("chat");requestAnimationFrame(resize);}
 async function attachImage(file?:File){const selected=file??fileRef.current?.files?.[0];if(!selected)return;if(!/^image\/(png|jpe?g|webp)$/i.test(selected.type)){setVoiceError("Use PNG, JPG, JPEG, or WebP.");return;}if(selected.size>12*1024*1024){setVoiceError("Image must be 12 MB or smaller.");return;}try{const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>typeof r.result==="string"?resolve(r.result):reject(new Error("Could not read image."));r.onerror=()=>reject(r.error||new Error("Could not read image."));r.readAsDataURL(selected);});setImageDataUrl(data);setImageName(selected.name);setVoiceError("");}catch(error){setVoiceError(error instanceof Error?error.message:"Could not attach image.");}}
 function voice(){const sw=window as SpeechWindow;const Recognition=sw.SpeechRecognition??sw.webkitSpeechRecognition;setVoiceError("");if(!Recognition){setVoiceError("Voice input is not supported in this browser.");return;}if(listening){recognitionRef.current?.stop();return;}const recognition=new Recognition();recognition.lang=navigator.language||"en-IN";recognition.continuous=false;recognition.interimResults=false;recognition.onresult=(event)=>{const text=event.results[0]?.[0]?.transcript??"";if(text)setValue(v=>v+(v?" ":"")+text);};recognition.onerror=(event)=>{setListening(false);recognitionRef.current=null;setVoiceError(event.error==="not-allowed"?"Microphone permission was denied.":"Voice input could not start. Try again.");};recognition.onend=()=>{setListening(false);recognitionRef.current=null;};recognitionRef.current=recognition;setListening(true);try{recognition.start();}catch{setListening(false);recognitionRef.current=null;setVoiceError("Voice input could not start. Try again.");}}
 const intent=detectRequestIntent(value),detectedMode=mediaModeForIntent(intent),mediaMode=manualMode==="chat"?detectedMode:manualMode;const researchActive=webSearch||intent==="research";const modeLabel=mediaMode==="pexels-photo"?"Pexels photos detected":mediaMode==="pexels-video"?"Pexels videos detected":researchActive?"Research detected":"";
 return <div className="composer-wrap"><div className="composer">{(imageDataUrl||modeLabel)&&<div className="attachment-chip">{imageDataUrl&&<img src={imageDataUrl} alt="Attached image preview"/>}<span>{imageName||modeLabel}</span>{imageDataUrl&&<button type="button" aria-label="Remove attached image" onClick={()=>{setImageDataUrl("");setImageName("");}}>×</button>}</div>}
 <textarea ref={inputRef} value={value} onChange={e=>{setValue(e.target.value);setVoiceError("");requestAnimationFrame(resize);}} onInput={resize} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void submit();}}} placeholder={mediaMode==="pexels-photo"?"Search Pexels photos…":mediaMode==="pexels-video"?"Search Pexels videos…":busy?"Ambi is responding…":"Message Ambi…"} rows={1} aria-label="Message Ambi"/>
 <input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void attachImage(e.target.files?.[0])}/>
 <div className="composer-row"><div className="composer-tools"><button className={`tool ${researchActive?"active":""}`} onClick={onToggleResearch} type="button" aria-pressed={researchActive}>⌁ Research</button><button className={`tool ${listening?"active":""}`} onClick={voice} type="button">{listening?"◉ Listening":"◉ Voice"}</button><button className="tool" onClick={()=>fileRef.current?.click()} type="button">⌕ Attach</button><button className={`tool ${mediaMode==="pexels-photo"?"active":""}`} onClick={()=>setManualMode(m=>m==="pexels-photo"?"chat":"pexels-photo")} type="button" aria-pressed={mediaMode==="pexels-photo"}>▧ Photos</button><button className={`tool ${mediaMode==="pexels-video"?"active":""}`} onClick={()=>setManualMode(m=>m==="pexels-video"?"chat":"pexels-video")} type="button" aria-pressed={mediaMode==="pexels-video"}>▷ Videos</button></div><span className="hint">{modeLabel||(imageDataUrl?"Attached image ready":"Shift+Enter for a new line")}</span>{busy?<button className="send stop" onClick={onStop} type="button">Stop</button>:<button className="send" onClick={()=>void submit()} type="button" disabled={!value.trim()}>{mediaMode==="pexels-photo"?"Search photos":mediaMode==="pexels-video"?"Search videos":"Send"}</button>}</div>{voiceError&&<div className="composer-error" role="status">{voiceError}</div>}</div></div>;
}